spring.application.name=nosso-carrinho-api

spring.datasource.url=jdbc:postgresql://${URL_DATABASE}/carrinho
spring.datasource.username=${USER_DATABASE}
spring.datasource.password=${PASSWORD_DATABASE}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
